# Generated by Django 4.1 on 2022-08-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_gender', models.CharField(max_length=10, verbose_name='Пол')),
                ('person_firstname', models.CharField(max_length=50, verbose_name='Имя')),
                ('person_lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('person_shortname', models.CharField(max_length=50, verbose_name='Короткое имя')),
                ('person_email_adress', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('person_phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('person_information', models.CharField(max_length=500, verbose_name='Обо мне')),
                ('person_interests', models.CharField(max_length=500, verbose_name='Хобби')),
                ('person_found', models.CharField(max_length=10, verbose_name='Зачем я здесь')),
                ('person_photo', models.ImageField(blank=True, upload_to='photos/%Y/&m/%d/', verbose_name='Фото')),
            ],
        ),
    ]
