# Generated by Django 4.1 on 2022-09-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='person_email_adress',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='people',
            name='person_firstname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='people',
            name='person_found',
            field=models.CharField(max_length=10, verbose_name='Кого ищу'),
        ),
        migrations.AlterField(
            model_name='people',
            name='person_information',
            field=models.CharField(blank=True, max_length=500, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='people',
            name='person_interests',
            field=models.CharField(blank=True, max_length=500, verbose_name='Хобби'),
        ),
        migrations.AlterField(
            model_name='people',
            name='person_lastname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='people',
            name='person_phone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер телефона'),
        ),
    ]
